export * from './svg/backArrow';
export * from './svg/email';
export * from './svg/eye';
export * from './svg/eyeOff';
export * from './svg/padLock';
export * from './svg/phone';
export * from './svg/user';
export * from './svg/onBoarding1';
export * from './svg/onBoarding2';
export * from './svg/onBoarding3';
export * from './svg/statisticsIcon';
export * from './svg/settingsIcon';
export * from './svg/myCardICon';
export * from './svg/homeIcon';
export * from './svg/search';
export * from './svg/wifi';
export * from './svg/cardChip';
export * from './svg/masterCard';
import ProfileImagem from './images/profile.png';
import CardBg from './images/cardBg.png';

export { ProfileImagem, CardBg };
